services:
  postgres:
    container_name: stocktrak_postgres
    image: postgres
    environment:
      POSTGRES_USER: thiago
      POSTGRES_PASSWORD: root 
      POSTGRES_DB: stocktrak
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - stocktrak-network

networks:
  stocktrak-network:
    driver: bridge

volumes:
  postgres_data:
